from __future__ import annotations

import csv
from pathlib import Path

DATA_DIR = Path("data")
OUTPUT_FILE = DATA_DIR / "cases.csv"

FIELDNAMES = [
    "case_id",
    "title",
    "symptom",
    "topology_note",
    "show_outputs",
    "expected_fault",
    "osi_layer",
    "concept",
    "severity",
    "expected_next_command",
    "expected_fix",
    "pc_ip",
    "pc_mask",
    "pc_gateway",
    "interface_status",
    "required_vlan",
    "known_vlans",
    "destination_network",
    "route_table",
    "peer_ips",
]


def case(
    case_id: str,
    title: str,
    symptom: str,
    topology_note: str,
    show_outputs: str,
    expected_fault: str,
    osi_layer: str,
    concept: str,
    severity: str,
    expected_next_command: str,
    expected_fix: str,
    **checker_fields: str,
) -> dict[str, str]:
    row = {field: "" for field in FIELDNAMES}
    row.update(
        {
            "case_id": case_id,
            "title": title,
            "symptom": symptom,
            "topology_note": topology_note,
            "show_outputs": show_outputs,
            "expected_fault": expected_fault,
            "osi_layer": osi_layer,
            "concept": concept,
            "severity": severity,
            "expected_next_command": expected_next_command,
            "expected_fix": expected_fix,
        }
    )
    row.update(checker_fields)
    return row


CASES = [
    case(
        "NS-001",
        "Access port assigned to wrong VLAN",
        "PC-A receives 192.168.20.21 but should be in VLAN 10 and cannot reach 192.168.10.1.",
        "PC-A connects to SW1 Fa0/3. VLAN 10 is the staff VLAN.",
        "show interfaces fa0/3 switchport:\nAdministrative Mode: static access\nAccess Mode VLAN: 20\n"
        "show vlan brief:\n10 STAFF active Fa0/1,Fa0/2\n20 GUEST active Fa0/3",
        "SW1 Fa0/3 is assigned to VLAN 20 instead of VLAN 10.",
        "Layer 2",
        "VLAN",
        "Medium",
        "show running-config interface fa0/3",
        "Configure interface Fa0/3 as switchport mode access and switchport access vlan 10.",
        pc_ip="192.168.20.21",
        pc_mask="255.255.255.0",
        pc_gateway="192.168.10.1",
        interface_status="up/up",
        required_vlan="10",
        known_vlans="10;20",
        peer_ips="192.168.10.11;192.168.10.12",
    ),
    case(
        "NS-002",
        "Required VLAN missing",
        "New finance PC cannot communicate with other finance devices.",
        "Finance devices should use VLAN 30 on SW1.",
        "show vlan brief:\n1 default active Fa0/1,Fa0/2,Fa0/8\n10 STAFF active\n20 GUEST active\n"
        "show interfaces fa0/8 switchport:\nAccess Mode VLAN: 30 (Inactive)",
        "VLAN 30 has not been created on SW1.",
        "Layer 2",
        "VLAN",
        "Medium",
        "show vlan brief",
        "Create VLAN 30, name it FINANCE, and confirm Fa0/8 is assigned to it.",
        interface_status="up/up",
        required_vlan="30",
        known_vlans="1;10;20",
    ),
    case(
        "NS-003",
        "Trunk does not allow VLAN 30",
        "Hosts in VLAN 30 communicate on the same switch but not across switches.",
        "SW1 and SW2 connect through Gi0/1 as an 802.1Q trunk.",
        "show interfaces trunk:\nPort Gi0/1 Mode on Encapsulation 802.1q Status trunking\n"
        "Vlans allowed on trunk: 10,20\nVlans active: 10,20,30",
        "VLAN 30 is missing from the allowed VLAN list on the trunk.",
        "Layer 2",
        "Trunk",
        "High",
        "show running-config interface gi0/1",
        "Add VLAN 30 to the trunk allowed list on both ends and verify with show interfaces trunk.",
        interface_status="up/up",
        required_vlan="30",
        known_vlans="10;20;30",
    ),
    case(
        "NS-004",
        "Native VLAN mismatch",
        "Users report intermittent connectivity and native VLAN mismatch messages.",
        "SW1 Gi0/1 trunks to SW2 Gi0/1.",
        "SW1 show interfaces trunk:\nGi0/1 native vlan 99\n"
        "SW1 log: %CDP-4-NATIVE_VLAN_MISMATCH: Native VLAN mismatch discovered on Gi0/1 (99), with SW2 Gi0/1 (1)",
        "The trunk endpoints use different native VLANs.",
        "Layer 2",
        "Trunk",
        "Medium",
        "show interfaces trunk",
        "Configure the same native VLAN on both trunk endpoints and ensure that VLAN exists.",
        interface_status="up/up",
        required_vlan="99",
        known_vlans="1;10;20;99",
    ),
    case(
        "NS-005",
        "Incorrect default gateway",
        "PC-B can ping local hosts but cannot reach any remote subnet.",
        "PC-B is in 192.168.10.0/24. Router gateway is 192.168.10.1.",
        "PC-B ipconfig:\nIP Address 192.168.10.25\nSubnet Mask 255.255.255.0\nDefault Gateway 192.168.20.1\n"
        "R1 show ip interface brief:\nG0/0 192.168.10.1 up up",
        "PC-B has a default gateway outside its local subnet.",
        "Layer 3",
        "Gateway",
        "High",
        "ipconfig /all",
        "Set PC-B's default gateway to 192.168.10.1.",
        pc_ip="192.168.10.25",
        pc_mask="255.255.255.0",
        pc_gateway="192.168.20.1",
        interface_status="up/up",
    ),
    case(
        "NS-006",
        "Wrong subnet mask",
        "PC-C can reach some local addresses but treats 192.168.10.200 as remote.",
        "All staff devices use 192.168.10.0/24.",
        "PC-C ipconfig:\nIP Address 192.168.10.20\nSubnet Mask 255.255.255.128\nDefault Gateway 192.168.10.1",
        "PC-C uses /25 instead of the required /24 subnet mask.",
        "Layer 3",
        "Addressing",
        "Medium",
        "ipconfig /all",
        "Change the PC subnet mask to 255.255.255.0.",
        pc_ip="192.168.10.20",
        pc_mask="255.255.255.128",
        pc_gateway="192.168.10.1",
        peer_ips="192.168.10.200",
    ),
    case(
        "NS-007",
        "Duplicate static IP address",
        "PC-D experiences intermittent connectivity and duplicate-address warnings.",
        "PC-D and a printer are connected to VLAN 10.",
        "PC-D ipconfig:\nIP Address 192.168.10.50\n"
        "R1 show ip arp:\n192.168.10.50 0011.2233.4455 ARPA G0/0\n"
        "SW1 show mac address-table:\n0011.2233.4455 Fa0/8\n00aa.bbcc.ddee Fa0/9",
        "Two devices are configured with 192.168.10.50.",
        "Layer 3",
        "Duplicate IP",
        "High",
        "show ip arp",
        "Assign a unique IP address to one device or reserve unique DHCP addresses.",
        pc_ip="192.168.10.50",
        pc_mask="255.255.255.0",
        pc_gateway="192.168.10.1",
        peer_ips="192.168.10.12;192.168.10.50;192.168.10.60",
    ),
    case(
        "NS-008",
        "Switch port administratively down",
        "PC-E has no link light and cannot obtain an IP address.",
        "PC-E connects to SW1 Fa0/12.",
        "show interfaces status:\nFa0/12 disabled 1 auto auto 10/100BaseTX\n"
        "show running-config interface fa0/12:\ninterface FastEthernet0/12\n shutdown",
        "SW1 Fa0/12 is administratively shut down.",
        "Layer 1",
        "Interface",
        "High",
        "show interfaces fa0/12",
        "Enter interface configuration mode and issue no shutdown.",
        interface_status="administratively down/down",
    ),
    case(
        "NS-009",
        "Physical interface down",
        "A branch router cannot communicate with the headquarters router.",
        "R1 G0/1 connects directly to R2 G0/1.",
        "R1 show ip interface brief:\nGigabitEthernet0/1 10.0.12.1 YES manual down down",
        "The physical link on R1 G0/1 is down.",
        "Layer 1",
        "Interface",
        "Critical",
        "show interfaces gigabitEthernet0/1",
        "Check cable and peer interface, correct the connection, and enable both interfaces.",
        interface_status="down/down",
    ),
    case(
        "NS-010",
        "DHCP service disabled",
        "Clients assign themselves 169.254.x.x addresses.",
        "Server0 should provide DHCP for VLAN 10.",
        "Server0 DHCP service: Off\nPC ipconfig:\nAutoconfiguration IP Address 169.254.22.7",
        "The DHCP service is disabled on Server0.",
        "Layer 7",
        "DHCP",
        "High",
        "show ip dhcp binding",
        "Enable the DHCP service and verify the VLAN 10 pool configuration.",
        pc_ip="169.254.22.7",
        pc_mask="255.255.0.0",
        interface_status="up/up",
    ),
    case(
        "NS-011",
        "DHCP pool has wrong default router",
        "Clients receive valid addresses but cannot leave their subnet.",
        "R1 G0/0 uses 192.168.10.1/24.",
        "show ip dhcp pool:\nPool VLAN10\nNetwork 192.168.10.0 /24\nDefault router 192.168.20.1\n"
        "PC ipconfig:\n192.168.10.101 /24 gateway 192.168.20.1",
        "The VLAN 10 DHCP pool supplies the wrong default gateway.",
        "Layer 7",
        "DHCP",
        "High",
        "show running-config | section dhcp",
        "Set default-router 192.168.10.1 in the VLAN 10 DHCP pool and renew client leases.",
        pc_ip="192.168.10.101",
        pc_mask="255.255.255.0",
        pc_gateway="192.168.20.1",
        interface_status="up/up",
    ),
    case(
        "NS-012",
        "DHCP pool exhausted",
        "Existing PCs work, but newly connected PCs cannot obtain addresses.",
        "The DHCP pool contains ten usable addresses.",
        "show ip dhcp pool VLAN20:\nTotal addresses: 10\nLeased addresses: 10\nExcluded addresses: 0\n"
        "show ip dhcp binding: 10 active bindings",
        "The DHCP address pool is exhausted.",
        "Layer 7",
        "DHCP",
        "Medium",
        "show ip dhcp binding",
        "Expand the pool or remove stale bindings after verifying they are no longer needed.",
        interface_status="up/up",
    ),
    case(
        "NS-013",
        "Missing DHCP relay",
        "VLAN 30 clients cannot get DHCP, while VLAN 10 clients can.",
        "The DHCP server is 192.168.10.10. VLAN 30 gateway is R1 G0/0.30.",
        "show running-config interface g0/0.30:\nencapsulation dot1Q 30\nip address 192.168.30.1 255.255.255.0\n"
        "No ip helper-address is configured.",
        "The VLAN 30 gateway lacks an IP helper address for the remote DHCP server.",
        "Layer 3",
        "DHCP Relay",
        "High",
        "show running-config interface g0/0.30",
        "Configure ip helper-address 192.168.10.10 on G0/0.30.",
        pc_ip="169.254.10.5",
        pc_mask="255.255.0.0",
        pc_gateway="",
        interface_status="up/up",
    ),
    case(
        "NS-014",
        "Incorrect DNS server address",
        "PC-F can ping 10.10.10.20 but cannot open server.example.local.",
        "The correct DNS server is 192.168.10.53.",
        "PC-F ipconfig /all:\nDNS Servers 192.168.10.99\n"
        "ping 10.10.10.20: success\nnslookup server.example.local: request timed out",
        "PC-F is configured with an incorrect DNS server address.",
        "Layer 7",
        "DNS",
        "Medium",
        "ipconfig /all",
        "Set the DNS server to 192.168.10.53 and repeat nslookup.",
        pc_ip="192.168.10.40",
        pc_mask="255.255.255.0",
        pc_gateway="192.168.10.1",
        interface_status="up/up",
    ),
    case(
        "NS-015",
        "Missing DNS record",
        "All clients can reach the web server by IP but not by hostname.",
        "DNS service is running on 192.168.10.53.",
        "nslookup portal.example.local:\nServer: 192.168.10.53\n*** can't find portal.example.local: Non-existent domain\n"
        "ping 10.10.10.20: success",
        "The DNS server has no record for portal.example.local.",
        "Layer 7",
        "DNS",
        "Medium",
        "nslookup portal.example.local",
        "Add the correct A record for portal.example.local and retest name resolution.",
        interface_status="up/up",
    ),
    case(
        "NS-016",
        "Missing static route",
        "R1 can reach the R2 transit address but cannot reach LAN 192.168.30.0/24.",
        "R1 and R2 connect over 10.0.12.0/30.",
        "R1 show ip route:\nC 192.168.10.0/24 is directly connected\nC 10.0.12.0/30 is directly connected\n"
        "No route for 192.168.30.0/24",
        "R1 has no route to 192.168.30.0/24.",
        "Layer 3",
        "Routing",
        "High",
        "show ip route 192.168.30.0",
        "Add a route to 192.168.30.0/24 through 10.0.12.2 or advertise it dynamically.",
        interface_status="up/up",
        destination_network="192.168.30.0/24",
        route_table="192.168.10.0/24;10.0.12.0/30",
    ),
    case(
        "NS-017",
        "Wrong static-route next hop",
        "Traffic to the branch LAN leaves R1 but fails immediately.",
        "R2's transit address is 10.0.12.2.",
        "show running-config | include ip route:\nip route 192.168.30.0 255.255.255.0 10.0.12.3\n"
        "show ip arp: no entry for 10.0.12.3",
        "The static route uses nonexistent next hop 10.0.12.3.",
        "Layer 3",
        "Routing",
        "High",
        "show ip route 192.168.30.0",
        "Replace the static route next hop with 10.0.12.2.",
        interface_status="up/up",
        destination_network="192.168.30.0/24",
        route_table="192.168.10.0/24;10.0.12.0/30;192.168.30.0/24",
    ),
    case(
        "NS-018",
        "OSPF network not advertised",
        "Other routers do not learn the VLAN 30 network.",
        "R1 runs OSPF process 1. VLAN 30 is 192.168.30.0/24.",
        "show ip protocols:\nRouting Protocol is ospf 1\nRouting for Networks:\n192.168.10.0 0.0.0.255 area 0\n10.0.12.0 0.0.0.3 area 0",
        "The VLAN 30 network is missing from the OSPF configuration.",
        "Layer 3",
        "OSPF",
        "High",
        "show running-config | section router ospf",
        "Advertise 192.168.30.0/24 in the correct OSPF area.",
        interface_status="up/up",
        destination_network="192.168.30.0/24",
        route_table="192.168.10.0/24;10.0.12.0/30",
    ),
    case(
        "NS-019",
        "OSPF area mismatch",
        "Two connected routers do not become OSPF neighbors.",
        "R1 and R2 share 10.0.12.0/30.",
        "R1 show ip ospf interface g0/1:\nArea 0\n"
        "R2 show ip ospf interface g0/1:\nArea 1\n"
        "show ip ospf neighbor: no neighbors",
        "The routers configure the shared link in different OSPF areas.",
        "Layer 3",
        "OSPF",
        "High",
        "show ip ospf interface g0/1",
        "Place both link interfaces in the same OSPF area.",
        interface_status="up/up",
    ),
    case(
        "NS-020",
        "RIP passive interface prevents updates",
        "The branch does not learn routes from R1, although the serial link is up.",
        "RIPv2 is used between R1 and R2.",
        "show ip protocols:\nPassive Interface(s): Serial0/0/0\nRouting for Networks: 10.0.0.0, 192.168.10.0",
        "The transit interface is passive, so RIP updates are not sent.",
        "Layer 3",
        "RIP",
        "Medium",
        "show running-config | section router rip",
        "Remove the passive-interface setting from the transit link and verify learned routes.",
        interface_status="up/up",
        destination_network="192.168.30.0/24",
        route_table="192.168.10.0/24;10.0.12.0/30",
    ),
    case(
        "NS-021",
        "ACL blocks required web traffic",
        "VLAN 20 users can ping the server but cannot access HTTP.",
        "An extended ACL is applied inbound on VLAN 20.",
        "show access-lists 110:\n10 deny tcp 192.168.20.0 0.0.0.255 host 10.10.10.20 eq 80 (25 matches)\n"
        "20 permit ip any any\nping 10.10.10.20: success",
        "ACL 110 explicitly denies HTTP from VLAN 20 to the server.",
        "Layer 4",
        "ACL",
        "High",
        "show access-lists 110",
        "Modify ACL 110 to permit the approved HTTP flow and preserve required security restrictions.",
        interface_status="up/up",
    ),
    case(
        "NS-022",
        "ACL applied in wrong direction",
        "The intended VLAN 30 restriction has no effect.",
        "ACL 120 should filter traffic entering R1 from VLAN 30.",
        "show ip interface g0/0.30:\nOutgoing access list is 120\nInbound access list is not set",
        "ACL 120 is applied outbound instead of inbound on the VLAN 30 interface.",
        "Layer 3/4",
        "ACL",
        "High",
        "show ip interface g0/0.30",
        "Remove the outbound application and apply ACL 120 inbound after reviewing its rules.",
        interface_status="up/up",
    ),
    case(
        "NS-023",
        "Implicit ACL deny",
        "Only the explicitly permitted admin host can reach the server; all other approved users fail.",
        "ACL 130 contains one permit statement.",
        "show access-lists 130:\n10 permit ip host 192.168.10.10 host 10.10.10.20\n"
        "No broader permit follows the entry.",
        "Traffic is denied by the ACL's implicit deny because required permit rules are missing.",
        "Layer 3/4",
        "ACL",
        "High",
        "show access-lists 130",
        "Add narrowly scoped permit entries for approved traffic before the implicit deny.",
        interface_status="up/up",
    ),
    case(
        "NS-024",
        "NAT inside and outside reversed",
        "Internal hosts reach the edge router but cannot access the simulated internet.",
        "G0/0 faces the LAN and G0/1 faces the ISP.",
        "show running-config interface g0/0:\nip nat outside\n"
        "show running-config interface g0/1:\nip nat inside\n"
        "show ip nat translations: empty",
        "NAT inside and outside roles are assigned to the wrong interfaces.",
        "Layer 3",
        "NAT",
        "High",
        "show running-config | include ip nat",
        "Configure G0/0 as ip nat inside and G0/1 as ip nat outside.",
        interface_status="up/up",
    ),
    case(
        "NS-025",
        "NAT ACL excludes the LAN",
        "LAN 192.168.20.0/24 cannot reach the internet, but VLAN 10 can.",
        "NAT overload uses ACL 1.",
        "show access-lists 1:\npermit 192.168.10.0 0.0.0.255\n"
        "show running-config:\nip nat inside source list 1 interface g0/1 overload",
        "The NAT ACL does not include 192.168.20.0/24.",
        "Layer 3",
        "NAT",
        "High",
        "show access-lists 1",
        "Add the approved VLAN 20 subnet to the NAT match criteria and verify translations.",
        interface_status="up/up",
    ),
    case(
        "NS-026",
        "Missing NAT overload",
        "Only one internal host can use the public interface address at a time.",
        "Many private hosts share one ISP-facing address.",
        "show running-config:\nip nat inside source list 1 interface g0/1\n"
        "The overload keyword is absent.",
        "PAT overload is missing from the dynamic NAT statement.",
        "Layer 3/4",
        "NAT",
        "High",
        "show ip nat statistics",
        "Replace the NAT statement with an approved overload configuration.",
        interface_status="up/up",
    ),
    case(
        "NS-027",
        "Wireless client uses wrong SSID",
        "A laptop cannot associate with the staff wireless network.",
        "The access point advertises SSID CorpWiFi.",
        "Laptop wireless profile:\nSSID CorpWifi-Guest\nStatus: Not associated\n"
        "AP configuration:\nSSID CorpWiFi",
        "The laptop is configured for the wrong SSID.",
        "Layer 2",
        "Wireless",
        "Low",
        "show wireless association",
        "Select CorpWiFi and use the approved security settings.",
        interface_status="up/up",
    ),
    case(
        "NS-028",
        "Wireless security key mismatch",
        "The client sees CorpWiFi but authentication fails.",
        "The AP uses WPA2-PSK.",
        "AP: WPA2-PSK key LabSecure2026\nClient: WPA2-PSK key LabSecure2025\nAuthentication failed",
        "The wireless pre-shared key on the client does not match the AP.",
        "Layer 2",
        "Wireless",
        "Medium",
        "show wireless security",
        "Configure the approved matching pre-shared key on the client without exposing it in logs.",
        interface_status="up/up",
    ),
    case(
        "NS-029",
        "Guest wireless mapped to internal VLAN",
        "Guest Wi-Fi users can reach an internal server.",
        "Guest SSID should map to VLAN 40 and be isolated from internal networks.",
        "AP mapping:\nSSID Guest -> VLAN 10\n"
        "SW1 VLANs:\n10 INTERNAL\n40 GUEST\n"
        "ping 10.10.10.20 from guest: success",
        "The Guest SSID is mapped to internal VLAN 10 instead of isolated VLAN 40.",
        "Layer 2/3",
        "Wireless Security",
        "Critical",
        "show wireless vlan mapping",
        "Map Guest to VLAN 40 and enforce a reviewed ACL that blocks internal access.",
        interface_status="up/up",
        required_vlan="40",
        known_vlans="10;40",
    ),
    case(
        "NS-030",
        "Router-on-a-stick encapsulation mismatch",
        "VLAN 30 clients can ping one another but cannot ping their gateway.",
        "R1 G0/0.30 should terminate VLAN 30.",
        "show running-config interface g0/0.30:\nencapsulation dot1Q 20\n"
        "ip address 192.168.30.1 255.255.255.0",
        "Subinterface G0/0.30 uses 802.1Q VLAN 20 instead of VLAN 30.",
        "Layer 2/3",
        "Inter-VLAN Routing",
        "High",
        "show running-config interface g0/0.30",
        "Change the subinterface encapsulation to dot1Q 30 and verify the switch trunk.",
        interface_status="up/up",
        required_vlan="30",
        known_vlans="10;20;30",
    ),
    case(
        "NS-031",
        "Spanning Tree blocking redundant path",
        "Traffic does not use SW2 Gi0/2, but the network remains reachable.",
        "SW2 has redundant Layer 2 links to the distribution switch.",
        "show spanning-tree vlan 10:\nGi0/1 Root FWD\nGi0/2 Altn BLK",
        "No fault: STP is intentionally blocking a redundant path to prevent a loop.",
        "Layer 2",
        "STP",
        "Low",
        "show spanning-tree vlan 10",
        "Do not force the port to forwarding. Verify the intended root bridge and redundant design.",
        interface_status="up/up",
    ),
    case(
        "NS-032",
        "Port security violation",
        "A replacement PC has link but cannot send traffic through Fa0/15.",
        "Fa0/15 permits one sticky MAC address.",
        "show port-security interface fa0/15:\nPort Status: secure-shutdown\nViolation Mode: shutdown\n"
        "Security Violation Count: 1",
        "Port security placed Fa0/15 in secure-shutdown after detecting a different MAC address.",
        "Layer 2",
        "Port Security",
        "High",
        "show port-security address",
        "Verify the replacement device, update the permitted MAC if authorized, and recover the port.",
        interface_status="err-disabled/down",
    ),
]


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    with OUTPUT_FILE.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(CASES)

    print(f"Created {len(CASES)} cases in {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
